### ISSUE TITLE
"No test runner in your project. Please install one." error

### ISSUE THREAD

**Issue by samsmithnz** [felixjb/testify#107]
**Describe the bug**
After installing the extension in a javascript based codespace project, I get the error `No test runner in your project. Please install one.`

**To Reproduce**

1. Create new JavaScript/Mocha project in Codespaces
2. Install this extension.
3. Click on codelens to run test

**Expected behavior**
Test should run

**Screenshots/GIFs**
error displayed `No test runner in your project. Please install one.`

![Image](https://github.com/felixjb/testify/assets/8389039/b386500d-dd98-4994-b9b6-c22c6c0a166c)

**Platform:**

- OS: Codespaces

**Test Framework:**

- Mocha, 10.2.0

**Additional context**
Can't find anything in the docs about how to resolve this. I'm essentially a JavaScript noob, so it's likely I've missed something, or a big assumption was made. Either way, would be nice to support new users/common troubleshooting issues somewhere.

**Comment by felixjb** [comment]
Hello @samsmithnz

You need to install the test runner to be able to use Testify. In your case, you mentioned you are using Mocha, so you need to install Mocha on your development environment first.
