### ISSUE TITLE
Fix Enzyme Internal Error

### ISSUE THREAD

**Issue by rebecamorais** [felixjb/testify#20]
**Describe the bug**
When using enzyme lib at jsx files, I'm not able to sucessfuly run the tests. 

**To Reproduce**
1. Go to a test.jsx that uses enzyme.
2. Try to run a test
3. See error

**Expected behavior**
 ```
Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
          To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:

          import Adapter from 'enzyme-adapter-react-15';

          To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html
```
**Screenshots**
![image](https://user-images.githubusercontent.com/17869927/63118738-de684e00-bf74-11e9-8f1e-69d3ccfd0612.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by felixjb** [comment]
Thank you for reporting the problem! I'll try to reproduce it here.

**Comment by rebecamorais** [comment]
Problem solved, thanks Félix.

If you used javascript-test-runner before
Go to /.vscode/settings.json and change this line:
`"javascript-test-runner.additionalArgs": "--setupTestFrameworkScriptFile=./config/jest/setupTests.js"`
to:
`"testify.additionalArgs": "--setupTestFrameworkScriptFile=./config/jest/setupTests.js"`
