### ISSUE TITLE
Regexp .test method triggers adding the "Run Test | Debug Test"

### ISSUE THREAD

**Issue by ricardomatias** [felixjb/testify#32]
**Describe the bug**
RegExp test method should not trigger the extension.

**To Reproduce**
Work on a javascript file.

**Expected behavior**
Nothing get's added

**Screenshots**
<img width="589" alt="Screenshot 2019-08-30 at 13 13 57" src="https://user-images.githubusercontent.com/8850708/64016883-68451900-cb28-11e9-9e59-e8e3914d3265.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version 10.14.6

**Comment by felixjb** [comment]
Hi! Thank you so much for contributing with this issue. 
That indeed shouldn't happen. I'll work on it. It might take a little while though, as I will have to change the parser.

**Comment by LoveSponge** [comment]
i'm picking this up.

**Comment by felixjb** [comment]
Should have been closed automatically when PR was merge 🤷🏽‍♂️
