### ISSUE TITLE
there is a undefined in grep

### ISSUE THREAD

**Issue by luxuze** [felixjb/testify#44]
**Describe the bug**
node_modules/.bin/mocha packages/ticket-backend/tests/services/Desk+Service.test.ts --grep="undefined" --require ts-node/register --exit

**Screenshots**

 luxuze@luxuzes-MacBook-Pro  ~/agora/web-monorepo   master  node_modules/.bin/mocha packages/ticket-backend/tests/services/Desk+Service.test.ts --grep="undefined" --require ts-node/register --exit

  0 passing (1ms)

 luxuze@luxuzes-MacBook-Pro  ~/agora/web-monorepo   master  node_modules/.bin/mocha packages/ticket-backend/tests/services/Desk+Service.test.ts --grep="Show Desks" --require ts-node/register --exit

  Test Desk+Service
    ✓ Show Desks (324ms)

  1 passing (335ms)
**Desktop (please complete the following information):**
 - OS: OS X

**Comment by felixjb** [comment]
Hi @luxuze ! Thank you for opening this issue!
Would you mind posting a screenshot of the test that presented this bug so I can have more information on it?

**Comment by luxuze** [comment]
<img width="1243" alt="WeChat4945aaa9aa72f1f2b0b5aee96eb0c17d" src="https://user-images.githubusercontent.com/35137889/67996648-387ed280-fc8b-11e9-9b47-ea744ca78986.png">

notice that the test case name is "undefined", but it work in the other .test.ts file.

**Comment by felixjb** [comment]
It's getting an `undefined` value in the grep because you are using the grave accent (`) instead of quotes.

I don't know if the Mocha or Jest test frameworks should work with template strings, so I will have to check on that.

**Comment by luxuze** [comment]
I replace ` with quotes,  and that test case worked, thank you !

**Comment by felixjb** [comment]
You're welcome! 
I will research on Mocha's grep capabilities an see if it should work with template strings too. 
And thank you again for contacting us!
