### ISSUE TITLE
 This experimental syntax requires enabling the parser plugin: 'optionalChaining' (55:12)

### ISSUE THREAD

**Issue by bradennapier** [felixjb/testify#54]
at ```/.vscode-insiders/extensions/felixjb.testify-1.4.0/node_modules/@babel/parser/lib/index.js:6344:17)
...
.vscode-insiders/extensions/felixjb.testify-1.4.0/out/parser/codeParser.js:11:26)```

**Comment by felixjb** [comment]
Hello @bradennapier !

Sorry for taking so long to respond. 

I tested the extension on a few projects using the optional chaining feature of TypeScript and didn't have any problems. However, I noticed that this is a feature that sometimes needs configuration depending on what tools you're using on your project, Babel being one of those.

Have you tried configuring Babel to work with this feature?
