### ISSUE TITLE
Babel's typescript transpilation options

### ISSUE THREAD

**Issue by calebboyd** [felixjb/testify#60]
**Describe the bug**

Decorators and metadata are unsupported and cause the extension to break
`[2020-08-16 07:22:56.183] [exthost] [error] SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (31:4)`

**To Reproduce**
Create a file with the following contents
```
function noop(target: any) {
  void 0
}
describe('something', () => {
  it('should work', () => {
    @noop
    class Test {}
  })
})
```

**Expected behavior**

Expected transpilation to occur according to tsconfig.json 

eg. [babel's configuration](https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options)

Specifically, support for:
 --emitDecoratorMetadata
 --experimentalDecorators

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.6.1

**Comment by felixjb** [comment]
Hello @calebboyd ! Thank you for reporting this. I will try to reproduced and might be opening a PR soon.
