### ISSUE TITLE
Incorrectly identifies identifier with name "it" as a test

### ISSUE THREAD

**Issue by forivall** [felixjb/testify#65]
Issue Type: <b>Bug</b>

Declare a variable with the name "it" and access a property on it using bracket notation. In my case, I use "it" as short for "item" and i'm accessing a symbol on it named "KEY", so `it[KEY]`, and testify shows a codeLens above that property access. when i click it, it runs a test for the testName "KEY"

I found this using the new vscode extension bisect tool; looking at your currently open issues, it's probably part of  https://github.com/felixjb/testify/issues/32 - however, it doesn't look like #61 would fix it.

A setting to disable the codelens for this extension would also be nice.

Extension version: 1.7.0
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 19, 14|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id 8fe9c0a9-e20f-435b-9c29-daef6bc63196|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

**Comment by felixjb** [comment]
Hello @forivall . I tried to reproduce the issue but  couldn't.

Would you please post a snippet of the code that yields the bug or a print of what's happening?

**Comment by felixjb** [comment]
Should have been closed automatically when PR was merge 🤷🏽‍♂️
