### ISSUE TITLE
Support for jest-each

### ISSUE THREAD

**Issue by roggenbrot** [felixjb/testify#66]
Current testify implementation does not support parametrized test with [jest-each](https://www.npmjs.com/package/jest-each). 

Since `jest-each` is changing the test name on runtime based on the import parameters, running the test will fail since jest will not find a valid test based on the test name pattern at runtime.

*Example:*

```javascript
  each`
  folder       | name
  ${undefined} | ${"New Name"}
  ${1}         | ${undefined}
  ${1}         | ${"New Name"}
`.test(
    "assert edit of $folder and $name",
    async (folder, name) => {
    ...
    });
```

In the example the following jest cli command is executed and will not find any test

```
node_modules/.bin/jest src/...........spec.tsx --testNamePattern="assert edit of $folder and $name" --coverage=false
Test Suites: 1 skipped, 0 of 1 total
Tests:       3 skipped, 3 total
Snapshots:   0 total
Time:        3.795 s, estimated 20 s
```

Since parsing of the test parameters with babel is impossible (There are multiple ways parameters can be defined and they can also contain logic like functions, variables ....)  the best way to support such test would replacing the parameter placeholder in the test name with a regex.

```
node_modules/.bin/jest src/...........spec.tsx --testNamePattern="assert edit of .* and .*" --coverage=false
```

**Comment by felixjb** [comment]
Should have been closed automatically when PR was merge 🤷🏽‍♂️
