### ISSUE TITLE
Double quotes should be escaped from the command

### ISSUE THREAD

**Issue by BigsonLvrocha** [felixjb/testify#75]
**Describe the bug**
If there is a test with `"` character, it will not be escaped and the command will be wrong, potentially running every tests

**To Reproduce**
1. Make a test with `"` in description
2. Click on run test
3. See terminal command
4. See all tests running or command failing

**Expected behavior**
`"` should be transormed into `\"` in command

**Screenshots**
![Captura de tela de 2021-08-04 11-29-57](https://user-images.githubusercontent.com/14062008/128199519-e0e4b3ad-4e85-44d0-83db-4e4c8d71ddb8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Version 1.9.0

**Comment by felixjb** [comment]
Hello @BigsonLvrocha !

Have you tried to run this test using the command line just to verify that Jest is able to understand that syntax?

**Comment by felixjb** [comment]
Fixed in the latest version!
