### ISSUE TITLE
Recognize test tokens without requiring a string literal

### ISSUE THREAD

**Issue by briancavalier** [felixjb/testify#78]
Thanks for this nice extension!  I've used others in the past, and just discovered testify today.  It seems to work great for our TypeScript project (using the additional args setting for esbuild-register) and feels lightweight and snappy.

**Is your feature request related to a problem? Please describe.**

My team at [Paceline](https://paceline.fit) uses `__filename` and `functionToTest.name` in mocha's `describe`.  For example, most of our test files look like:

```ts
import { describe, it } from 'mocha'
import { functionToTest } from './moduleToTest'

describe(__filename, () => {
  describe(functionToTest.name, () => {
    it('given x, returns y', () => {
      // ...
    })
    // more it()s ...
  })
})
```

We find that this reduces the burden of thinking of names, and reduces test maintenance since it works well with automatic refactorings in many IDEs (moving files, renaming functions, etc.).

**Describe the solution you'd like**

It'd be great if testify could recognize test tokens that don't [include a string literal](https://github.com/felixjb/testify/blob/main/src/parser/codeParser.ts#L64).  If that would cause a problem with testify having false positives--thinking things are tests when they aren't--then, maybe allowing a template string literal in addition to a string literal is a viable alternative.

That would allow wrapping in a template string literal:

```ts
describe(`${__filename}`, () => {
  describe(`${functionToTest.name}`, () => {
    it('given x, returns y', () => {
```

**Describe alternatives you've considered**

It'd be totally fine if this was opt-in via settings, if that would also help reduce false positives for folks who prefer using string literals.

**Additional context**

Example of testify recignizing the `it()`s with string literals, but not recognizing `describe()`s without string literals.

<img width="605" alt="Screen Shot 2022-04-14 at 3 15 02 PM" src="https://user-images.githubusercontent.com/90518/163460553-48c31226-c043-4edb-9375-91ece01dd073.png">

**Comment by briancavalier** [comment]
I'd be happy to submit a PR if you decide this is a reasonable feature to add, @felixjb.

**Comment by felixjb** [comment]
Hello! I'm sorry for taking so long to respond. I'll take a look into it and come back with an answer

**Comment by felixjb** [comment]
Hi @briancavalier , here's what I found:

During transpilation I don't think it's possible to evaluate a variable or template string to get a test name to execute te command on the terminal. However, apparently, the `__filename` and `identifier.name` are things that could be available to the parser during transpilation. 

I'll try to work on it during this week but probably will have more time during next week.

Feel free to open a PR if you feel comfortable enough!

**Comment by briancavalier** [comment]
Hey @felixjb, thanks for looking into it.  If the parser does have access to `__filename` and `identifier.name`, that sounds like it could be a perfect fit for our use case.

I probably won't have time until at least the weekend, but if I do start working on something, I'll let you know.

> I don't think it's possible to evaluate a variable or template string to get a test name to execute te command on the terminal

That makes perfect sense.  I just noticed that testify ultimately uses mocha's fgrep to specify which tests to run, so I can see why it'd need access to the fully evaluated description string.

**Comment by felixjb** [comment]
Hello @briancavalier 

Just letting you know that I haven't forgotten this. I am trying to make time to work on it but I haven't gotten any yet.

**Comment by briancavalier** [comment]
Thanks for the update, @felixjb

**Comment by felixjb** [comment]
@briancavalier I just found out that the VSCode API has now some new features regarding testing. I think I am going to spend some time learning how to use them. Maybe we'll be able to do better with this feature, who knows.

**Comment by briancavalier** [comment]
Sounds good, @felixjb

**Comment by felixjb** [comment]
Hello @briancavalier

After some research and testing I got to the conclusion that this feature cannot be implemented, at least not without some major changes in the project.

Quick recap for anyone who comes looking into this the future:

Testify, as it is now (version 1.9.0), uses Babel parser to parse the source code and find any tokens related to test frameworks, like `describe` and `test`. Then, with the location of these tokens in the file and the value of the `title` argument of these test function calls, which is a `StringLiteral`, it opens a new terminal and sends a command to execute the test with the local test framework. This command filters the tests in the codebase by using an argument that takes the title of the test.

During the parsing of the file, Babel, as far as I know, cannot evaluate a variable, like `__filename`, and return its value. It also cannot evaluate a `TemplateString`. Without a test name, Testify cannot execute the command to run that specific test.

Now for the good news: 

VSCode release a native API for working with tests and I think there are some good opportunities there. However, this may require some rework in our project, which I am willing to do, but will take some time. Until then, feel free to reach out! Maybe I'll make more use of the discussions section on this repo.

**Comment by briancavalier** [comment]
Hey @felixjb, I really appreciate all your research and communication on this.  It's a bummer for now, but I completely understand.  I'll look forward to a future version that uses those new VSCode features 😄 

Thanks again for looking into it and for testify!

**Comment by felixjb** [comment]
You're welcome! And you're always welcome to open new issues and pull requests!
